<?php

/**
 * PluginsfFaqCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfFaqCategoryTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginsfFaqCategoryTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginsfFaqCategory');
  }

  /*
   * retrieves all items ordered by name
   * 
   */
  public function retrieveAll()
  {
    return Doctrine::getTable('sfFaqCategory')
      ->createQuery('a')
      ->orderBy('a.name asc')
      ->execute();
  }

  /*
   * retrieves first item ordered by name
   * 
   */
  public function retrieveFirst()
  {
    return Doctrine::getTable('sfFaqCategory')
      ->createQuery('a')
      ->orderBy('a.name asc')
      ->fetchOne();
  }

}
