<?php

/**
 * PluginsfFaqCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfDoctrineFaqPlugin
 * @subpackage model
 * @author     Susan Lau <susan.lau@gmx.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginsfFaqCategory extends BasesfFaqCategory
{
  public function __toString()
  {
    return $this->getName();
  }

  public function getsfFaqFaqs()
  {

    return Doctrine::getTable('sfFaqFaq')
      ->createQuery('a')
      ->where('a.category_id = ?', $this->getId())
      ->orderBy('a.question asc')
      ->execute();

  }
}
